.TH "$FGC/some-componenet" "2" " Container Image Pages" "Steve Milner" "October 2018" 
.nh
.ad l


.SH NAME
.PP
$FGC/some\-componenet \- A key\-value store for shared configuration and service discovery.


.SH DESCRIPTION
.PP
Long description documentation comes from the comments at the start of the Dockerfile. Note that spaces at the end of the line one each comment may be needed for formatting.

.PP
If you want to have a second paragraph then add a comment line with nothing on it.


.SH USAGE
.PP
/usr/bin/docker run \-\-cap\-add NET\_ADMIN \-d \-\-cap\-add=SYS\_ADMIN  \-p 4001:4001 \-p 7001:7001 \-p 2379:2379 \-p 2380:2380


.SH Default Command
.PP
/usr/bin/etcd\-env.sh /usr/bin/etcd


.SH ENVIRONMENT VARIABLES
.PP
The image recognizes the following environment variables that you can set
during initialization by passing \fB\fC\-e VAR=VALUE\fR to the \fB\fCdocker run\fR command.

.TS
allbox;
l l l 
l l l .
\fB\fCVariable name\fR	\fB\fCDefault\fR	\fB\fCDescription\fR
\fB\fCVERSION\fR	\fB\fC0.1\fR	T{
Denotes the version of this dockerfile
T}
\fB\fCRELEASE\fR	\fB\fC10\fR	T{
Denotes the release of this dockerfile
T}
\fB\fCARCH\fR	\fB\fCx86\_64\fR	Denotes the architecture
.TE


.SH SECURITY IMPLICATIONS
.PP
The following sections describe potential security issues related to how the container image was designed to run.

.SH Ports
.PP
Exposed TCP (default) or UDP ports that the container listens on at runtime include the following:

.TS
allbox;
l l l 
l l l .
\fB\fCPort Container\fR	\fB\fCPort Host\fR	\fB\fCDescription\fR
4001	4001	Use for something
7001	7001	Used for something else
2379	2379	Used for the another thing
2380	2380	Used for the last thing
.TE

.SH Volumes
.PP
Directories that are mounted from the host system to a mount point inside the container include the following:

.TS
allbox;
l l l 
l l l .
\fB\fCVolume Container\fR	\fB\fCVolume Host\fR	\fB\fCDescription\fR
/test	/tmp/test	A test mount
/something	/tmp/something	Another test mount
/else	/tmp/else	The else test mount
/another	/var/tmp/another	The last test mount
.TE

.SH Daemon
.PP
This image is expected to be run as a daemon

.SH Expected Capabilities
.PP
This container needs to open one or more Linux capabilities (see \fB\fCman capabilities 7\fR) to the host computer. The following capababilities (added with the \-\-cap\-add option) are expected:

.RS
.IP \(bu 2
NET\_ADMIN
.IP \(bu 2
SYS\_ADMIN

.RE


.SH SEE ALSO
.PP

\[la]http://example.org/asd/asd\[ra]

\[la]http://example.org/sdgfsdf\[ra]
