.TH "$FGC/some-componenet" "2" " Container Image Pages" "Steve Milner" "December 2017" 
.nh
.ad l


.SH NAME
.PP
$FGC/some\-componenet \- A key\-value store for shared configuration and service discovery.


.SH DESCRIPTION
.PP
TODO


.SH USAGE
.PP
/usr/bin/docker run \-d \-p 4001:4001 \-p 7001:7001 \-p 2379:2379 \-p 2380:2380


.SH ENVIRONMENT VARIABLES
.PP
The image recognizes the following environment variables that you can set
during initialization be passing \fB\fC\-e VAR=VALUE\fR to the Docker run command.

.TS
allbox;
l l l 
l l l .
\fB\fCVariable name\fR	\fB\fCDefault\fR	\fB\fCDescription\fR
\fB\fCVERSION\fR	\fB\fC0.1\fR	TODO
\fB\fCRELEASE\fR	\fB\fC10\fR	TODO
\fB\fCARCH\fR	\fB\fCx86\_64\fR	TODO
.TE


.SH SECURITY IMPLICATIONS
.SH Ports
.TS
allbox;
l l l 
l l l .
\fB\fCPort Container\fR	\fB\fCPort Host\fR	\fB\fCDescription\fR
4001	0	TODO
7001	0	TODO
2379	0	TODO
2380	0	TODO
.TE

.SH Volumes
.TS
allbox;
l l l 
l l l .
\fB\fCVolume Container\fR	\fB\fCVolume Host\fR	\fB\fCDescription\fR
/test	TODO	TODO
/something	TODO	TODO
/else	TODO	TODO
/another	TODO	TODO
.TE


.SH SEE ALSO
.PP

\[la]http://example.org/asd/asd\[ra]
