language: go

go:
  - 1.8
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false
#  irc: "irc.freenode.org#atomic"
#  skip_join: false

# Required since the clone will not always be tested from inside the same namespace
before_script:
  - mkdir -p $HOME/gopath/src/github.com/ashcrow/image-helpgen/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/ashcrow/image-helpgen/

script:
  - make lint
  - make deps
  - dep status
  - make test
  - make build
  - make e2e
